name: CI
on: [push]

jobs:
  build-blst-linux-amd64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build amd64
        run: ./run.me
        working-directory: ./blst/bindings/java

      - uses: actions/upload-artifact@v3
        with:
          name: linux-amd64
          path: ./blst/bindings/java/supranational/blst/Linux

  build-blst-linux-aarch64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build aarch64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          install: |
            apt-get update -q -y
            apt-get install -q -y git wget apt-transport-https swig gcc binutils g++
            mkdir -p /etc/apt/keyrings
            wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | tee /etc/apt/keyrings/adoptium.asc
            echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
            apt-get update -q -y
            apt-get install -q -y temurin-11-jdk

          run: |
            cd blst/bindings/java
            ./run.me
            mv blst/bindings/java/supranational /artifacts/

      - name: Check
        run: ls -al ./artifacts

      - uses: actions/upload-artifact@v3
        with:
          name: linux-aarch64
          path: ./artifacts/blst/Linux
