name: CI
on: [push]

jobs:
  build-blst-linux-amd64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build blst
        run: ./run.me
        working-directory: ./blst/bindings/java

      - uses: actions/upload-artifact@v3
        with:
          name: linux-amd64
          path: ./blst/bindings/java/supranational/blst/Linux

  build-blst-linux-aarch64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build blst
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          install: |
            apt-get update -q -y
            apt-get install -q -y git wget apt-transport-https swig gcc binutils g++
            mkdir -p /etc/apt/keyrings
            wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | tee /etc/apt/keyrings/adoptium.asc
            echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
            apt-get update -q -y
            apt-get install -q -y temurin-11-jdk

          run: |
            cd blst/bindings/java
            ./run.me
            mv ./supranational /artifacts/

      - name: Check
        run: ls -al ./artifacts

      - uses: actions/upload-artifact@v3
        with:
          name: linux-aarch64
          path: ./artifacts/blst/Linux

  build-blst-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name:  Build arm64
        run: ./build.sh
        working-directory: ./blst
        env:
          CC: "cc -arch arm64"
          CXX: "c++ -arch arm64 -std=c++11"

      - name: Build bindings arm64
        run: ./build.sh
        working-directory: ./blst/bindings/java
        env:
          CC: "cc -arch arm64"
          CXX: "c++ -arch arm64 -std=c++11"

      - run: mv ./x86_64 ./aarch64
        working-directory: ./blst/bindings/java/supranational/blst/Mac

      - run: rm -rf libblst.a supranational.blst.jar
        working-directory: ./blst/bindings/java

      - name:  Build amd64
        run: ./build.sh
        working-directory: ./blst

      - name: Build blst
        run: ./run.me
        working-directory: ./blst/bindings/java

      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: ./blst/bindings/java/supranational/blst/Mac
